export const ATTACK_MODES = {
  SELECT_SLASH: 'SELECT_SLASH',
  JOIN_WAVE: 'JOIN_WAVE',
  WHERE_STRIKE: 'WHERE_STRIKE',
  GROUP_BY_SHOCKWAVE: 'GROUP_BY_SHOCKWAVE',
  JOIN_STORM: 'JOIN_STORM',
  GROUP_BY_EXPLOSION: 'GROUP_BY_EXPLOSION',
  DELETE_FROM: 'DELETE_FROM',
} as const

export type AttackMode = (typeof ATTACK_MODES)[keyof typeof ATTACK_MODES]

export const ATTACK_MODE_LABELS: Record<AttackMode, string> = {
  [ATTACK_MODES.SELECT_SLASH]: 'SELECT Slash',
  [ATTACK_MODES.JOIN_WAVE]: 'JOIN Wave',
  [ATTACK_MODES.WHERE_STRIKE]: 'WHERE Precision Strike',
  [ATTACK_MODES.GROUP_BY_SHOCKWAVE]: 'GROUP BY Shockwave',
  [ATTACK_MODES.JOIN_STORM]: 'JOIN Storm',
  [ATTACK_MODES.GROUP_BY_EXPLOSION]: 'GROUP BY Explosion',
  [ATTACK_MODES.DELETE_FROM]: 'DELETE FROM',
}
