export const SCENE_KEYS = {
  BOOT: 'BootScene',
  TITLE: 'TitleScene',
  GAME: 'GameScene',
  UI: 'UIScene',
  GAME_OVER: 'GameOverScene',
} as const

export const ENTITY_CATEGORIES = {
  PLAYER: 'player',
  ENEMY: 'enemy',
  PICKUP: 'pickup',
  BOSS: 'boss',
} as const

export const ENEMY_IDS = {
  CI_CD_BOT: 'CI_CD_BOT',
  ORCHESTRATOR: 'ORCHESTRATOR',
  AUTOMATOR_SWARM: 'AUTOMATOR_SWARM',
  MEETING_MONSTER: 'MEETING_MONSTER',
  BURNOUT_GHOST: 'BURNOUT_GHOST',
  EXCEL_ZOMBIE: 'EXCEL_ZOMBIE',
  SLACK_NOTIFIER: 'SLACK_NOTIFIER',
  LEGACY_MONOLITH: 'LEGACY_MONOLITH',
} as const

export const BOSS_IDS = {
  THERAPIST_BOSS: 'THERAPIST_BOSS',
} as const

export const PICKUP_IDS = {
  PUMPKIN_LATTE: 'PUMPKIN_LATTE',
  NEW_MACBOOK: 'NEW_MACBOOK',
  THERAPY_SESSION: 'THERAPY_SESSION',
  STACKOVERFLOW_SCROLL: 'STACKOVERFLOW_SCROLL',
  VACATION_TICKET: 'VACATION_TICKET',
  NOISE_CANCELLING_AIRPODS: 'NOISE_CANCELLING_AIRPODS',
  SECOND_MONITOR: 'SECOND_MONITOR',
  PYTHON_SCRIPT: 'PYTHON_SCRIPT',
  EXCEL_MACRO: 'EXCEL_MACRO',
  JUPYTER_NOTEBOOK: 'JUPYTER_NOTEBOOK',
  CHATGPT_PROMPT: 'CHATGPT_PROMPT',
  GIT_BLAME: 'GIT_BLAME',
  DUCKDUCKGO_QUERY: 'DUCKDUCKGO_QUERY',
  POWERPOINT_DECK: 'POWERPOINT_DECK',
} as const

export const GAME_EVENTS = {
  PLAYER_HIT: 'PLAYER_HIT',
  ENEMY_KILLED: 'ENEMY_KILLED',
  PICKUP_COLLECTED: 'PICKUP_COLLECTED',
  BOSS_SPAWNED: 'BOSS_SPAWNED',
  SCORE_CHANGED: 'SCORE_CHANGED',
  GAME_OVER: 'GAME_OVER',
} as const
